FROM alpine:latest
RUN \
    apk add --no-cache \
    apache2-proxy \
    apache2-ssl \
    apache2-utils \
    curl \
    git \
    logrotate \
    openssl
WORKDIR /var/www/localhost/htdocs

COPY ecommerce-webapp/index.html /var/www/localhost/htdocs
COPY ecommerce-webapp/index.css  /var/www/localhost/htdocs
COPY ecommerce-webapp/index.js /var/www/localhost/htdocs
COPY ecommerce-webapp/media /var/www/localhost/htdocs
EXPOSE 80
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]

